project_id = "mefwbcbnctqjxrwldmjm"

[functions.fetch-tech-news]
verify_jwt = false

[functions.automation-engine]
verify_jwt = false

[functions.send-idea-confirmation]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.send-mentor-approval-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.email-tracking]
verify_jwt = false

[functions.send-mentor-rejection-email]
verify_jwt = false

[functions.process-scheduled-newsletters]
verify_jwt = false
